snr: 0
cur_str: percrerun
num_snrs: 1
n_ants: 8
snr_step: 1
n_users: 2
mcs: 5
mod_pilot: -1
block_length_factor: 5
num_res: 1
cfo: 0
clip_percentage_in_tx: 100
iqmm_gain: 0 # in dB
iqmm_phase: 0 # in degrees
epochs: 2
iterations: 1
batch_size: 32
shuffle: True

learning_rate: 1e-3 # 5.0e-4
pilot_size: 40
kernel_size: 3
stag_re_kernel_size: 3
full_e2e: True
ber_on_one_user: -1
sphere_radius: 200
save_loss_plot_snr: [40]
use_film: False
scale_input: True
override_noise_var: False
make_64QAM_16QAM_percentage: 100
increase_prime_modulation: True  # QPSK→16QAM or 16QAM→64QAM based on mod_pilot

use_data_as_pilots: False
plot_only_last_iteration: False
plot_channel: False
plot_genie: False

TDL_model: 'C'
delay_spread: 300e-9 # in Seconds
carrier_frequency: 2.6e9 # in Hz
speed: 0 # in m/s
spatial_correlation: 'medium' # Options: none, low, medium, medium_a, high, custom
pilot_channel_seed: -1
channel_seed: 17

run_deeprx: False
run_deepsic: False
run_deepsicmb: False
run_deepstag: False
run_mhsa: False
run_sphere: False
run_tdcnn: False
run_tdfdcnn: False
which_augment: 'AUGMENT_SPHERE'
override_augment_with_lmmse: False

mhsa_no_probs: True

run_e2e: False
iters_e2e: 1
no_probs: False
separate_pilots: True



# general
seed: 0 # run seed

# channel
cfo_and_iqmm_in_rx: True



# validation phase protocol
block_length: -1 # 8004 2000 # coherence block time, total size of pilot + data. values: int.  - should be a multilpier of log2(mod_pilot)
blocks_num: 1 # 100 number of validation frames. values: int.